### ISSUE TITLE
Implement a communication medium

### ISSUE THREAD

**Issue by samithkavishke** [oscarbenjamin/protosym#146]
#### Details
This repository currently doesnot have a proper channel to chat with contributors.

#### Solution
Implement a google group or slack channel for discussion, or moving this repository to an organization(Sympy) would enable discussion forum.

**Comment by oscarbenjamin** [comment]
I've just enabled GitHub discussions.

For a mailing list I would suggest to use the SymPy mailing list. Perhaps we should add a link to that somewhere. Feel free to send a pull request for that.
